/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardRouteRouteImport } from './routes/_onboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as OnboardAppRouteRouteImport } from './routes/_onboard/_app/route'
import { Route as AuthSignupRouteRouteImport } from './routes/_auth/signup/route'
import { Route as OnboardAppProfileRouteImport } from './routes/_onboard/_app/profile'
import { Route as OnboardAppHomeRouteImport } from './routes/_onboard/_app/home'
import { Route as AuthSignupCheckEmailRouteImport } from './routes/_auth/signup/check-email'

const OnboardRouteRoute = OnboardRouteRouteImport.update({
  id: '/_onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const OnboardAppRouteRoute = OnboardAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => OnboardRouteRoute,
} as any)
const AuthSignupRouteRoute = AuthSignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const OnboardAppProfileRoute = OnboardAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardAppRouteRoute,
} as any)
const OnboardAppHomeRoute = OnboardAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => OnboardAppRouteRoute,
} as any)
const AuthSignupCheckEmailRoute = AuthSignupCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthSignupRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof AuthSignupRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup/check-email': typeof AuthSignupCheckEmailRoute
  '/home': typeof OnboardAppHomeRoute
  '/profile': typeof OnboardAppProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof AuthSignupRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup/check-email': typeof AuthSignupCheckEmailRoute
  '/home': typeof OnboardAppHomeRoute
  '/profile': typeof OnboardAppProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_onboard': typeof OnboardRouteRouteWithChildren
  '/_auth/signup': typeof AuthSignupRouteRouteWithChildren
  '/_onboard/_app': typeof OnboardAppRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup/check-email': typeof AuthSignupCheckEmailRoute
  '/_onboard/_app/home': typeof OnboardAppHomeRoute
  '/_onboard/_app/profile': typeof OnboardAppProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/login'
    | '/signup/check-email'
    | '/home'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signup' | '/login' | '/signup/check-email' | '/home' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_onboard'
    | '/_auth/signup'
    | '/_onboard/_app'
    | '/_auth/login'
    | '/_auth/signup/check-email'
    | '/_onboard/_app/home'
    | '/_onboard/_app/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardRouteRoute: typeof OnboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_onboard': {
      id: '/_onboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_onboard/_app': {
      id: '/_onboard/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardAppRouteRouteImport
      parentRoute: typeof OnboardRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_onboard/_app/profile': {
      id: '/_onboard/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof OnboardAppProfileRouteImport
      parentRoute: typeof OnboardAppRouteRoute
    }
    '/_onboard/_app/home': {
      id: '/_onboard/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof OnboardAppHomeRouteImport
      parentRoute: typeof OnboardAppRouteRoute
    }
    '/_auth/signup/check-email': {
      id: '/_auth/signup/check-email'
      path: '/check-email'
      fullPath: '/signup/check-email'
      preLoaderRoute: typeof AuthSignupCheckEmailRouteImport
      parentRoute: typeof AuthSignupRouteRoute
    }
  }
}

interface AuthSignupRouteRouteChildren {
  AuthSignupCheckEmailRoute: typeof AuthSignupCheckEmailRoute
}

const AuthSignupRouteRouteChildren: AuthSignupRouteRouteChildren = {
  AuthSignupCheckEmailRoute: AuthSignupCheckEmailRoute,
}

const AuthSignupRouteRouteWithChildren = AuthSignupRouteRoute._addFileChildren(
  AuthSignupRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignupRouteRoute: typeof AuthSignupRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignupRouteRoute: AuthSignupRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OnboardAppRouteRouteChildren {
  OnboardAppHomeRoute: typeof OnboardAppHomeRoute
  OnboardAppProfileRoute: typeof OnboardAppProfileRoute
}

const OnboardAppRouteRouteChildren: OnboardAppRouteRouteChildren = {
  OnboardAppHomeRoute: OnboardAppHomeRoute,
  OnboardAppProfileRoute: OnboardAppProfileRoute,
}

const OnboardAppRouteRouteWithChildren = OnboardAppRouteRoute._addFileChildren(
  OnboardAppRouteRouteChildren,
)

interface OnboardRouteRouteChildren {
  OnboardAppRouteRoute: typeof OnboardAppRouteRouteWithChildren
}

const OnboardRouteRouteChildren: OnboardRouteRouteChildren = {
  OnboardAppRouteRoute: OnboardAppRouteRouteWithChildren,
}

const OnboardRouteRouteWithChildren = OnboardRouteRoute._addFileChildren(
  OnboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardRouteRoute: OnboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
