/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedCreateProfileRouteImport } from './routes/_authed/create-profile'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthedProfileRouteRouteImport } from './routes/_authed/_profile/route'
import { Route as AuthedProfileProfileRouteImport } from './routes/_authed/_profile/profile'
import { Route as AuthedProfileHomeRouteImport } from './routes/_authed/_profile/home'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCreateProfileRoute = AuthedCreateProfileRouteImport.update({
  id: '/create-profile',
  path: '/create-profile',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRouteRoute = AuthedProfileRouteRouteImport.update({
  id: '/_profile',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfileProfileRoute = AuthedProfileProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedProfileRouteRoute,
} as any)
const AuthedProfileHomeRoute = AuthedProfileHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/create-profile': typeof AuthedCreateProfileRoute
  '/home': typeof AuthedProfileHomeRoute
  '/profile': typeof AuthedProfileProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/create-profile': typeof AuthedCreateProfileRoute
  '/home': typeof AuthedProfileHomeRoute
  '/profile': typeof AuthedProfileProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_authed/_profile': typeof AuthedProfileRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authed/create-profile': typeof AuthedCreateProfileRoute
  '/_authed/_profile/home': typeof AuthedProfileHomeRoute
  '/_authed/_profile/profile': typeof AuthedProfileProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/create-profile'
    | '/home'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/create-profile' | '/home' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/_profile'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_authed/create-profile'
    | '/_authed/_profile/home'
    | '/_authed/_profile/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/create-profile': {
      id: '/_authed/create-profile'
      path: '/create-profile'
      fullPath: '/create-profile'
      preLoaderRoute: typeof AuthedCreateProfileRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_profile': {
      id: '/_authed/_profile'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedProfileRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/_profile/profile': {
      id: '/_authed/_profile/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileProfileRouteImport
      parentRoute: typeof AuthedProfileRouteRoute
    }
    '/_authed/_profile/home': {
      id: '/_authed/_profile/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedProfileHomeRouteImport
      parentRoute: typeof AuthedProfileRouteRoute
    }
  }
}

interface AuthedProfileRouteRouteChildren {
  AuthedProfileHomeRoute: typeof AuthedProfileHomeRoute
  AuthedProfileProfileRoute: typeof AuthedProfileProfileRoute
}

const AuthedProfileRouteRouteChildren: AuthedProfileRouteRouteChildren = {
  AuthedProfileHomeRoute: AuthedProfileHomeRoute,
  AuthedProfileProfileRoute: AuthedProfileProfileRoute,
}

const AuthedProfileRouteRouteWithChildren =
  AuthedProfileRouteRoute._addFileChildren(AuthedProfileRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedProfileRouteRoute: typeof AuthedProfileRouteRouteWithChildren
  AuthedCreateProfileRoute: typeof AuthedCreateProfileRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedProfileRouteRoute: AuthedProfileRouteRouteWithChildren,
  AuthedCreateProfileRoute: AuthedCreateProfileRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
